require("dotenv").config({ path: __dirname + "/.env" });
const mongoose = require("mongoose");
const Bank = require("./models/Bank");

mongoose.connect(process.env.MONGO_URI)
  .then(() => console.log("✅ MongoDB Connected:", process.env.MONGO_URI))
  .catch(err => { console.error("❌ Connection failed:", err.message); process.exit(1); });

const ALL_LOAN_TYPES = ["Home Loan", "Car Loan", "Personal Loan", "Education Loan", "Business Loan", "Gold Loan", "Loan Against Property"];

const banks = [
  // ─── MAJOR PUBLIC SECTOR BANKS ───
  { name: "State Bank of India",          type: "Public", riskCategory: "Low",    baseInterestRate: 8.10, processingFee: 0.30, maxLoanAmount: 50000000, minCreditScore: 700, loanTypes: ALL_LOAN_TYPES,                                              tenureRange: { min: 1, max: 30 }, eligibilityCriteria: { minIncome: 20000 } },
  { name: "Punjab National Bank",         type: "Public", riskCategory: "Low",    baseInterestRate: 8.40, processingFee: 0.35, maxLoanAmount: 30000000, minCreditScore: 710, loanTypes: ALL_LOAN_TYPES,                                              tenureRange: { min: 1, max: 30 }, eligibilityCriteria: { minIncome: 22000 } },
  { name: "Bank of Baroda",               type: "Public", riskCategory: "Low",    baseInterestRate: 8.55, processingFee: 0.40, maxLoanAmount: 25000000, minCreditScore: 700, loanTypes: ALL_LOAN_TYPES,                                              tenureRange: { min: 1, max: 30 }, eligibilityCriteria: { minIncome: 20000 } },
  { name: "Canara Bank",                  type: "Public", riskCategory: "Low",    baseInterestRate: 8.60, processingFee: 0.40, maxLoanAmount: 20000000, minCreditScore: 700, loanTypes: ALL_LOAN_TYPES,                                              tenureRange: { min: 1, max: 30 }, eligibilityCriteria: { minIncome: 18000 } },
  { name: "Bank of India",                type: "Public", riskCategory: "Low",    baseInterestRate: 8.65, processingFee: 0.45, maxLoanAmount: 20000000, minCreditScore: 695, loanTypes: ALL_LOAN_TYPES,                                              tenureRange: { min: 1, max: 30 }, eligibilityCriteria: { minIncome: 18000 } },
  { name: "Union Bank of India",          type: "Public", riskCategory: "Low",    baseInterestRate: 8.70, processingFee: 0.40, maxLoanAmount: 18000000, minCreditScore: 700, loanTypes: ALL_LOAN_TYPES,                                              tenureRange: { min: 1, max: 30 }, eligibilityCriteria: { minIncome: 20000 } },
  { name: "Central Bank of India",        type: "Public", riskCategory: "Medium", baseInterestRate: 8.85, processingFee: 0.50, maxLoanAmount: 15000000, minCreditScore: 690, loanTypes: ["Home Loan", "Car Loan", "Personal Loan", "Education Loan", "Business Loan", "Gold Loan"], tenureRange: { min: 1, max: 25 }, eligibilityCriteria: { minIncome: 18000 } },
  { name: "Indian Overseas Bank",         type: "Public", riskCategory: "Medium", baseInterestRate: 8.90, processingFee: 0.50, maxLoanAmount: 12000000, minCreditScore: 685, loanTypes: ["Home Loan", "Personal Loan", "Education Loan", "Gold Loan", "Loan Against Property"], tenureRange: { min: 1, max: 20 }, eligibilityCriteria: { minIncome: 17000 } },
  { name: "UCO Bank",                     type: "Public", riskCategory: "Medium", baseInterestRate: 8.95, processingFee: 0.55, maxLoanAmount: 10000000, minCreditScore: 680, loanTypes: ["Home Loan", "Personal Loan", "Education Loan", "Gold Loan"], tenureRange: { min: 1, max: 20 }, eligibilityCriteria: { minIncome: 16000 } },
  { name: "Punjab & Sind Bank",           type: "Public", riskCategory: "Medium", baseInterestRate: 8.80, processingFee: 0.45, maxLoanAmount: 10000000, minCreditScore: 685, loanTypes: ["Home Loan", "Car Loan", "Personal Loan", "Education Loan"], tenureRange: { min: 1, max: 20 }, eligibilityCriteria: { minIncome: 15000 } },
  { name: "Bank of Maharashtra",          type: "Public", riskCategory: "Medium", baseInterestRate: 8.75, processingFee: 0.45, maxLoanAmount: 12000000, minCreditScore: 690, loanTypes: ["Home Loan", "Car Loan", "Personal Loan", "Education Loan", "Gold Loan"], tenureRange: { min: 1, max: 25 }, eligibilityCriteria: { minIncome: 16000 } },
  { name: "Indian Bank",                  type: "Public", riskCategory: "Low",    baseInterestRate: 8.50, processingFee: 0.40, maxLoanAmount: 15000000, minCreditScore: 700, loanTypes: ALL_LOAN_TYPES,                                              tenureRange: { min: 1, max: 30 }, eligibilityCriteria: { minIncome: 18000 } },

  // ─── MAJOR PRIVATE SECTOR BANKS ───
  { name: "HDFC Bank",                    type: "Private", riskCategory: "Low",    baseInterestRate: 8.30, processingFee: 0.50, maxLoanAmount: 50000000, minCreditScore: 750, loanTypes: ALL_LOAN_TYPES,                                              tenureRange: { min: 1, max: 30 }, eligibilityCriteria: { minIncome: 30000 } },
  { name: "ICICI Bank",                   type: "Private", riskCategory: "Low",    baseInterestRate: 8.75, processingFee: 1.00, maxLoanAmount: 40000000, minCreditScore: 730, loanTypes: ALL_LOAN_TYPES,                                              tenureRange: { min: 1, max: 30 }, eligibilityCriteria: { minIncome: 28000 } },
  { name: "Axis Bank",                    type: "Private", riskCategory: "Medium", baseInterestRate: 9.00, processingFee: 1.00, maxLoanAmount: 30000000, minCreditScore: 720, loanTypes: ALL_LOAN_TYPES,                                              tenureRange: { min: 1, max: 25 }, eligibilityCriteria: { minIncome: 28000 } },
  { name: "Kotak Mahindra Bank",          type: "Private", riskCategory: "Low",    baseInterestRate: 8.65, processingFee: 0.75, maxLoanAmount: 35000000, minCreditScore: 740, loanTypes: ALL_LOAN_TYPES,                                              tenureRange: { min: 1, max: 25 }, eligibilityCriteria: { minIncome: 30000 } },
  { name: "IndusInd Bank",                type: "Private", riskCategory: "Medium", baseInterestRate: 9.25, processingFee: 1.00, maxLoanAmount: 20000000, minCreditScore: 700, loanTypes: ["Home Loan", "Car Loan", "Personal Loan", "Business Loan", "Gold Loan"], tenureRange: { min: 1, max: 20 }, eligibilityCriteria: { minIncome: 25000 } },
  { name: "Yes Bank",                     type: "Private", riskCategory: "Medium", baseInterestRate: 9.85, processingFee: 1.50, maxLoanAmount: 15000000, minCreditScore: 690, loanTypes: ["Home Loan", "Personal Loan", "Business Loan", "Loan Against Property"], tenureRange: { min: 1, max: 20 }, eligibilityCriteria: { minIncome: 25000 } },
  { name: "IDFC First Bank",              type: "Private", riskCategory: "Medium", baseInterestRate: 9.50, processingFee: 1.00, maxLoanAmount: 15000000, minCreditScore: 700, loanTypes: ["Home Loan", "Personal Loan", "Business Loan", "Education Loan"], tenureRange: { min: 1, max: 25 }, eligibilityCriteria: { minIncome: 25000 } },
  { name: "Federal Bank",                 type: "Private", riskCategory: "Low",    baseInterestRate: 8.80, processingFee: 0.50, maxLoanAmount: 15000000, minCreditScore: 700, loanTypes: ALL_LOAN_TYPES,                                              tenureRange: { min: 1, max: 25 }, eligibilityCriteria: { minIncome: 22000 } },
  { name: "South Indian Bank",            type: "Private", riskCategory: "Low",    baseInterestRate: 9.00, processingFee: 0.60, maxLoanAmount: 12000000, minCreditScore: 695, loanTypes: ["Home Loan", "Car Loan", "Personal Loan", "Gold Loan", "Education Loan"], tenureRange: { min: 1, max: 20 }, eligibilityCriteria: { minIncome: 20000 } },
  { name: "Karnataka Bank",               type: "Private", riskCategory: "Low",    baseInterestRate: 9.10, processingFee: 0.55, maxLoanAmount: 10000000, minCreditScore: 690, loanTypes: ["Home Loan", "Car Loan", "Personal Loan", "Gold Loan"], tenureRange: { min: 1, max: 20 }, eligibilityCriteria: { minIncome: 18000 } },
  { name: "City Union Bank",              type: "Private", riskCategory: "Medium", baseInterestRate: 9.30, processingFee: 0.75, maxLoanAmount: 10000000, minCreditScore: 680, loanTypes: ["Home Loan", "Personal Loan", "Business Loan", "Gold Loan"], tenureRange: { min: 1, max: 20 }, eligibilityCriteria: { minIncome: 18000 } },
  { name: "Jammu & Kashmir Bank",         type: "Private", riskCategory: "Medium", baseInterestRate: 9.15, processingFee: 0.60, maxLoanAmount: 10000000, minCreditScore: 685, loanTypes: ["Home Loan", "Car Loan", "Personal Loan", "Education Loan"], tenureRange: { min: 1, max: 20 }, eligibilityCriteria: { minIncome: 18000 } },
  { name: "Nainital Bank",                type: "Private", riskCategory: "Medium", baseInterestRate: 9.20, processingFee: 0.70, maxLoanAmount: 8000000,  minCreditScore: 680, loanTypes: ["Home Loan", "Personal Loan", "Gold Loan"],               tenureRange: { min: 1, max: 15 }, eligibilityCriteria: { minIncome: 15000 } },
  { name: "RBL Bank",                     type: "Private", riskCategory: "Medium", baseInterestRate: 10.25, processingFee: 1.50, maxLoanAmount: 10000000, minCreditScore: 680, loanTypes: ["Personal Loan", "Business Loan", "Home Loan"],            tenureRange: { min: 1, max: 15 }, eligibilityCriteria: { minIncome: 22000 } },
  { name: "Bandhan Bank",                 type: "Private", riskCategory: "High",   baseInterestRate: 11.00, processingFee: 1.80, maxLoanAmount: 5000000,  minCreditScore: 620, loanTypes: ["Personal Loan", "Business Loan", "Home Loan", "Gold Loan"], tenureRange: { min: 1, max: 15 }, eligibilityCriteria: { minIncome: 12000 } },
  { name: "DCB Bank",                     type: "Private", riskCategory: "Medium", baseInterestRate: 10.00, processingFee: 1.25, maxLoanAmount: 8000000,  minCreditScore: 670, loanTypes: ["Home Loan", "Personal Loan", "Loan Against Property"],   tenureRange: { min: 1, max: 20 }, eligibilityCriteria: { minIncome: 20000 } },
  { name: "Lakshmi Vilas Bank",           type: "Private", riskCategory: "Medium", baseInterestRate: 9.75, processingFee: 1.00, maxLoanAmount: 8000000,  minCreditScore: 675, loanTypes: ["Home Loan", "Gold Loan", "Personal Loan"],                tenureRange: { min: 1, max: 15 }, eligibilityCriteria: { minIncome: 18000 } },
  { name: "Dhanlaxmi Bank",               type: "Private", riskCategory: "Medium", baseInterestRate: 9.80, processingFee: 1.00, maxLoanAmount: 7000000,  minCreditScore: 670, loanTypes: ["Home Loan", "Gold Loan", "Personal Loan"],                tenureRange: { min: 1, max: 15 }, eligibilityCriteria: { minIncome: 16000 } },
  { name: "Saraswat Cooperative Bank",    type: "Private", riskCategory: "Low",    baseInterestRate: 8.95, processingFee: 0.60, maxLoanAmount: 10000000, minCreditScore: 700, loanTypes: ["Home Loan", "Car Loan", "Personal Loan", "Education Loan", "Gold Loan"], tenureRange: { min: 1, max: 20 }, eligibilityCriteria: { minIncome: 20000 } },
  { name: "Karur Vysya Bank",             type: "Private", riskCategory: "Low",    baseInterestRate: 9.05, processingFee: 0.55, maxLoanAmount: 10000000, minCreditScore: 695, loanTypes: ["Home Loan", "Car Loan", "Personal Loan", "Gold Loan"],    tenureRange: { min: 1, max: 20 }, eligibilityCriteria: { minIncome: 18000 } },
  { name: "Tamilnad Mercantile Bank",     type: "Private", riskCategory: "Low",    baseInterestRate: 9.15, processingFee: 0.60, maxLoanAmount: 10000000, minCreditScore: 690, loanTypes: ["Home Loan", "Personal Loan", "Gold Loan", "Car Loan"],     tenureRange: { min: 1, max: 20 }, eligibilityCriteria: { minIncome: 18000 } },

  // ─── SMALL FINANCE BANKS ───
  { name: "AU Small Finance Bank",        type: "Private", riskCategory: "Medium", baseInterestRate: 10.50, processingFee: 1.50, maxLoanAmount: 5000000,  minCreditScore: 650, loanTypes: ["Personal Loan", "Business Loan", "Home Loan", "Car Loan"], tenureRange: { min: 1, max: 15 }, eligibilityCriteria: { minIncome: 15000 } },
  { name: "Ujjivan Small Finance Bank",   type: "Private", riskCategory: "High",   baseInterestRate: 12.00, processingFee: 2.00, maxLoanAmount: 3000000,  minCreditScore: 620, loanTypes: ["Personal Loan", "Business Loan", "Home Loan"],            tenureRange: { min: 1, max: 10 }, eligibilityCriteria: { minIncome: 10000 } },
  { name: "Equitas Small Finance Bank",   type: "Private", riskCategory: "High",   baseInterestRate: 11.50, processingFee: 2.00, maxLoanAmount: 3000000,  minCreditScore: 630, loanTypes: ["Personal Loan", "Business Loan", "Home Loan"],            tenureRange: { min: 1, max: 10 }, eligibilityCriteria: { minIncome: 10000 } },
  { name: "Jana Small Finance Bank",      type: "Private", riskCategory: "High",   baseInterestRate: 12.50, processingFee: 2.00, maxLoanAmount: 2500000,  minCreditScore: 600, loanTypes: ["Personal Loan", "Business Loan"],                        tenureRange: { min: 1, max: 7  }, eligibilityCriteria: { minIncome: 8000  } },
  { name: "Suryoday Small Finance Bank",  type: "Private", riskCategory: "High",   baseInterestRate: 12.25, processingFee: 2.00, maxLoanAmount: 2500000,  minCreditScore: 610, loanTypes: ["Personal Loan", "Home Loan"],                            tenureRange: { min: 1, max: 10 }, eligibilityCriteria: { minIncome: 9000  } },
  { name: "ESAF Small Finance Bank",      type: "Private", riskCategory: "High",   baseInterestRate: 12.75, processingFee: 2.00, maxLoanAmount: 2000000,  minCreditScore: 600, loanTypes: ["Personal Loan", "Business Loan"],                        tenureRange: { min: 1, max: 7  }, eligibilityCriteria: { minIncome: 8000  } },
  { name: "Capital Small Finance Bank",   type: "Private", riskCategory: "High",   baseInterestRate: 11.75, processingFee: 1.75, maxLoanAmount: 2500000,  minCreditScore: 620, loanTypes: ["Personal Loan", "Home Loan", "Business Loan"],            tenureRange: { min: 1, max: 10 }, eligibilityCriteria: { minIncome: 10000 } },

  // ─── MAJOR NBFCs ───
  { name: "Bajaj Finance",                type: "NBFC", riskCategory: "Medium", baseInterestRate: 11.00, processingFee: 2.00, maxLoanAmount: 3500000,  minCreditScore: 650, loanTypes: ["Personal Loan", "Business Loan", "Home Loan"],            tenureRange: { min: 1, max: 7  }, eligibilityCriteria: { minIncome: 20000 } },
  { name: "Aditya Birla Finance",         type: "NBFC", riskCategory: "Medium", baseInterestRate: 10.75, processingFee: 1.75, maxLoanAmount: 5000000,  minCreditScore: 660, loanTypes: ["Personal Loan", "Business Loan", "Home Loan", "Loan Against Property", "Education Loan"], tenureRange: { min: 1, max: 10 }, eligibilityCriteria: { minIncome: 25000 } },
  { name: "Tata Capital",                 type: "NBFC", riskCategory: "Low",    baseInterestRate: 10.50, processingFee: 1.50, maxLoanAmount: 7500000,  minCreditScore: 680, loanTypes: ["Personal Loan", "Home Loan", "Business Loan", "Car Loan", "Education Loan"], tenureRange: { min: 1, max: 15 }, eligibilityCriteria: { minIncome: 25000 } },
  { name: "L&T Finance",                  type: "NBFC", riskCategory: "Low",    baseInterestRate: 9.75,  processingFee: 1.00, maxLoanAmount: 10000000, minCreditScore: 680, loanTypes: ["Home Loan", "Car Loan", "Business Loan", "Loan Against Property"], tenureRange: { min: 1, max: 20 }, eligibilityCriteria: { minIncome: 25000 } },
  { name: "Mahindra Finance",             type: "NBFC", riskCategory: "Medium", baseInterestRate: 10.25, processingFee: 1.50, maxLoanAmount: 5000000,  minCreditScore: 640, loanTypes: ["Car Loan", "Business Loan", "Personal Loan"],             tenureRange: { min: 1, max: 7  }, eligibilityCriteria: { minIncome: 15000 } },
  { name: "HDB Financial Services",       type: "NBFC", riskCategory: "Medium", baseInterestRate: 10.75, processingFee: 1.75, maxLoanAmount: 4000000,  minCreditScore: 650, loanTypes: ["Personal Loan", "Business Loan", "Home Loan", "Car Loan"], tenureRange: { min: 1, max: 10 }, eligibilityCriteria: { minIncome: 20000 } },
  { name: "Muthoot Finance",              type: "NBFC", riskCategory: "Medium", baseInterestRate: 12.00, processingFee: 1.00, maxLoanAmount: 5000000,  minCreditScore: 600, loanTypes: ["Gold Loan", "Personal Loan", "Business Loan"],            tenureRange: { min: 1, max: 3  }, eligibilityCriteria: { minIncome: 10000 } },
  { name: "Manappuram Finance",           type: "NBFC", riskCategory: "Medium", baseInterestRate: 12.25, processingFee: 1.00, maxLoanAmount: 4000000,  minCreditScore: 600, loanTypes: ["Gold Loan", "Personal Loan"],                            tenureRange: { min: 1, max: 3  }, eligibilityCriteria: { minIncome: 10000 } },
  { name: "Cholamandalam Finance",        type: "NBFC", riskCategory: "Medium", baseInterestRate: 10.50, processingFee: 1.50, maxLoanAmount: 5000000,  minCreditScore: 640, loanTypes: ["Car Loan", "Business Loan", "Loan Against Property"],      tenureRange: { min: 1, max: 7  }, eligibilityCriteria: { minIncome: 15000 } },
  { name: "Shriram Finance",              type: "NBFC", riskCategory: "High",   baseInterestRate: 13.00, processingFee: 2.00, maxLoanAmount: 3000000,  minCreditScore: 600, loanTypes: ["Car Loan", "Business Loan", "Personal Loan"],             tenureRange: { min: 1, max: 5  }, eligibilityCriteria: { minIncome: 12000 } },
  { name: "IIFL Finance",                 type: "NBFC", riskCategory: "Medium", baseInterestRate: 11.50, processingFee: 1.75, maxLoanAmount: 5000000,  minCreditScore: 640, loanTypes: ["Gold Loan", "Home Loan", "Business Loan"],               tenureRange: { min: 1, max: 10 }, eligibilityCriteria: { minIncome: 15000 } },
  { name: "Piramal Capital & Housing",    type: "NBFC", riskCategory: "Medium", baseInterestRate: 10.00, processingFee: 1.50, maxLoanAmount: 10000000, minCreditScore: 670, loanTypes: ["Home Loan", "Loan Against Property", "Business Loan"],    tenureRange: { min: 1, max: 20 }, eligibilityCriteria: { minIncome: 30000 } },
  { name: "PNB Housing Finance",          type: "NBFC", riskCategory: "Low",    baseInterestRate: 8.75,  processingFee: 0.75, maxLoanAmount: 15000000, minCreditScore: 700, loanTypes: ["Home Loan", "Loan Against Property"],                     tenureRange: { min: 1, max: 30 }, eligibilityCriteria: { minIncome: 25000 } },
  { name: "LIC Housing Finance",          type: "NBFC", riskCategory: "Low",    baseInterestRate: 8.50,  processingFee: 0.50, maxLoanAmount: 20000000, minCreditScore: 700, loanTypes: ["Home Loan", "Loan Against Property"],                     tenureRange: { min: 1, max: 30 }, eligibilityCriteria: { minIncome: 22000 } },
  { name: "GIC Housing Finance",          type: "NBFC", riskCategory: "Low",    baseInterestRate: 8.70,  processingFee: 0.50, maxLoanAmount: 12000000, minCreditScore: 695, loanTypes: ["Home Loan"],                                             tenureRange: { min: 1, max: 25 }, eligibilityCriteria: { minIncome: 20000 } },
  { name: "Indiabulls Housing Finance",   type: "NBFC", riskCategory: "Medium", baseInterestRate: 9.50,  processingFee: 1.25, maxLoanAmount: 10000000, minCreditScore: 675, loanTypes: ["Home Loan", "Loan Against Property", "Business Loan"],    tenureRange: { min: 1, max: 20 }, eligibilityCriteria: { minIncome: 25000 } },
  { name: "Fullerton India Credit",       type: "NBFC", riskCategory: "Medium", baseInterestRate: 11.25, processingFee: 2.00, maxLoanAmount: 3000000,  minCreditScore: 640, loanTypes: ["Personal Loan", "Business Loan"],                        tenureRange: { min: 1, max: 5  }, eligibilityCriteria: { minIncome: 15000 } },
  { name: "CreditAccess Grameen",         type: "NBFC", riskCategory: "High",   baseInterestRate: 14.50, processingFee: 2.00, maxLoanAmount: 1000000,  minCreditScore: 580, loanTypes: ["Personal Loan", "Business Loan"],                        tenureRange: { min: 1, max: 3  }, eligibilityCriteria: { minIncome: 8000  } },
  { name: "Spandana Sphoorty",            type: "NBFC", riskCategory: "High",   baseInterestRate: 14.00, processingFee: 2.00, maxLoanAmount: 1000000,  minCreditScore: 580, loanTypes: ["Personal Loan", "Business Loan"],                        tenureRange: { min: 1, max: 3  }, eligibilityCriteria: { minIncome: 7000  } },
  { name: "MAS Financial Services",       type: "NBFC", riskCategory: "High",   baseInterestRate: 13.50, processingFee: 2.00, maxLoanAmount: 2000000,  minCreditScore: 600, loanTypes: ["Personal Loan", "Business Loan", "Home Loan"],            tenureRange: { min: 1, max: 5  }, eligibilityCriteria: { minIncome: 10000 } },
  { name: "Veritas Finance",              type: "NBFC", riskCategory: "High",   baseInterestRate: 14.25, processingFee: 2.00, maxLoanAmount: 1500000,  minCreditScore: 590, loanTypes: ["Personal Loan", "Business Loan"],                        tenureRange: { min: 1, max: 3  }, eligibilityCriteria: { minIncome: 8000  } },

  // ─── FOREIGN BANKS (INDIA OPERATIONS) ───
  { name: "Citibank India",               type: "Private", riskCategory: "Low",    baseInterestRate: 9.99,  processingFee: 1.50, maxLoanAmount: 10000000, minCreditScore: 750, loanTypes: ["Personal Loan", "Home Loan", "Car Loan"],                tenureRange: { min: 1, max: 10 }, eligibilityCriteria: { minIncome: 40000 } },
  { name: "Standard Chartered India",     type: "Private", riskCategory: "Low",    baseInterestRate: 10.50, processingFee: 1.50, maxLoanAmount: 8000000,  minCreditScore: 750, loanTypes: ["Personal Loan", "Home Loan"],                            tenureRange: { min: 1, max: 10 }, eligibilityCriteria: { minIncome: 40000 } },
  { name: "Deutsche Bank India",          type: "Private", riskCategory: "Low",    baseInterestRate: 10.25, processingFee: 1.50, maxLoanAmount: 10000000, minCreditScore: 760, loanTypes: ["Personal Loan", "Loan Against Property", "Business Loan"], tenureRange: { min: 1, max: 10 }, eligibilityCriteria: { minIncome: 50000 } },
  { name: "HSBC India",                   type: "Private", riskCategory: "Low",    baseInterestRate: 9.75,  processingFee: 1.25, maxLoanAmount: 10000000, minCreditScore: 760, loanTypes: ["Personal Loan", "Home Loan"],                            tenureRange: { min: 1, max: 10 }, eligibilityCriteria: { minIncome: 50000 } },
  { name: "Barclays India",               type: "Private", riskCategory: "Medium", baseInterestRate: 11.00, processingFee: 1.75, maxLoanAmount: 5000000,  minCreditScore: 730, loanTypes: ["Personal Loan", "Business Loan"],                        tenureRange: { min: 1, max: 5  }, eligibilityCriteria: { minIncome: 35000 } },

  // ─── DIGITAL / FINTECH LENDERS ───
  { name: "Navi Technologies",            type: "NBFC", riskCategory: "Medium", baseInterestRate: 9.99,  processingFee: 0.00, maxLoanAmount: 2000000,  minCreditScore: 650, loanTypes: ["Personal Loan", "Home Loan"],                            tenureRange: { min: 1, max: 10 }, eligibilityCriteria: { minIncome: 15000 } },
  { name: "Stashfin Credit Line",         type: "NBFC", riskCategory: "High",   baseInterestRate: 11.99, processingFee: 1.50, maxLoanAmount: 500000,   minCreditScore: 620, loanTypes: ["Personal Loan"],                                        tenureRange: { min: 1, max: 3  }, eligibilityCriteria: { minIncome: 12000 } },
  { name: "KreditBee",                    type: "NBFC", riskCategory: "High",   baseInterestRate: 14.00, processingFee: 2.00, maxLoanAmount: 300000,   minCreditScore: 600, loanTypes: ["Personal Loan"],                                        tenureRange: { min: 1, max: 2  }, eligibilityCriteria: { minIncome: 10000 } },
  { name: "MoneyTap",                     type: "NBFC", riskCategory: "High",   baseInterestRate: 13.00, processingFee: 2.00, maxLoanAmount: 500000,   minCreditScore: 620, loanTypes: ["Personal Loan"],                                        tenureRange: { min: 1, max: 3  }, eligibilityCriteria: { minIncome: 12000 } },
  { name: "CASHe",                        type: "NBFC", riskCategory: "High",   baseInterestRate: 18.00, processingFee: 3.00, maxLoanAmount: 400000,   minCreditScore: 580, loanTypes: ["Personal Loan"],                                        tenureRange: { min: 1, max: 2  }, eligibilityCriteria: { minIncome: 10000 } },
  { name: "EarlySalary",                  type: "NBFC", riskCategory: "High",   baseInterestRate: 16.00, processingFee: 2.50, maxLoanAmount: 300000,   minCreditScore: 580, loanTypes: ["Personal Loan"],                                        tenureRange: { min: 1, max: 2  }, eligibilityCriteria: { minIncome: 10000 } },
  { name: "Lendingkart",                  type: "NBFC", riskCategory: "High",   baseInterestRate: 15.00, processingFee: 2.00, maxLoanAmount: 2000000,  minCreditScore: 600, loanTypes: ["Business Loan"],                                        tenureRange: { min: 1, max: 3  }, eligibilityCriteria: { minIncome: 12000 } },
  { name: "Flexi Loans India",            type: "NBFC", riskCategory: "High",   baseInterestRate: 14.50, processingFee: 2.00, maxLoanAmount: 1000000,  minCreditScore: 610, loanTypes: ["Business Loan", "Personal Loan"],                        tenureRange: { min: 1, max: 3  }, eligibilityCriteria: { minIncome: 12000 } },
  { name: "Indifi Technologies",          type: "NBFC", riskCategory: "High",   baseInterestRate: 15.50, processingFee: 2.00, maxLoanAmount: 1500000,  minCreditScore: 600, loanTypes: ["Business Loan"],                                        tenureRange: { min: 1, max: 3  }, eligibilityCriteria: { minIncome: 15000 } },
  { name: "CapFloat Financial",           type: "NBFC", riskCategory: "High",   baseInterestRate: 16.00, processingFee: 2.00, maxLoanAmount: 2000000,  minCreditScore: 600, loanTypes: ["Business Loan"],                                        tenureRange: { min: 1, max: 3  }, eligibilityCriteria: { minIncome: 15000 } },
  { name: "Rupee112",                     type: "NBFC", riskCategory: "High",   baseInterestRate: 14.00, processingFee: 2.00, maxLoanAmount: 500000,   minCreditScore: 600, loanTypes: ["Personal Loan"],                                        tenureRange: { min: 1, max: 2  }, eligibilityCriteria: { minIncome: 10000 } },
  { name: "Faircent Peer Lending",        type: "NBFC", riskCategory: "High",   baseInterestRate: 13.50, processingFee: 2.00, maxLoanAmount: 1000000,  minCreditScore: 620, loanTypes: ["Personal Loan", "Business Loan"],                        tenureRange: { min: 1, max: 3  }, eligibilityCriteria: { minIncome: 15000 } },
  { name: "i2iFunding",                   type: "NBFC", riskCategory: "High",   baseInterestRate: 15.00, processingFee: 2.00, maxLoanAmount: 500000,   minCreditScore: 600, loanTypes: ["Personal Loan", "Business Loan"],                        tenureRange: { min: 1, max: 3  }, eligibilityCriteria: { minIncome: 12000 } },
  { name: "Zwende Finance",               type: "NBFC", riskCategory: "High",   baseInterestRate: 17.00, processingFee: 3.00, maxLoanAmount: 300000,   minCreditScore: 580, loanTypes: ["Personal Loan"],                                        tenureRange: { min: 1, max: 2  }, eligibilityCriteria: { minIncome: 10000 } },

  // ─── HOUSING FINANCE COMPANIES ───
  { name: "HDFC Ltd (HFC)",               type: "NBFC", riskCategory: "Low",    baseInterestRate: 8.45,  processingFee: 0.50, maxLoanAmount: 30000000, minCreditScore: 720, loanTypes: ["Home Loan", "Loan Against Property"],                     tenureRange: { min: 1, max: 30 }, eligibilityCriteria: { minIncome: 25000 } },
  { name: "Bajaj Housing Finance",         type: "NBFC", riskCategory: "Low",    baseInterestRate: 8.50,  processingFee: 0.50, maxLoanAmount: 20000000, minCreditScore: 720, loanTypes: ["Home Loan", "Loan Against Property"],                     tenureRange: { min: 1, max: 30 }, eligibilityCriteria: { minIncome: 25000 } },
  { name: "Aavas Financiers",             type: "NBFC", riskCategory: "Medium", baseInterestRate: 9.90,  processingFee: 1.00, maxLoanAmount: 5000000,  minCreditScore: 650, loanTypes: ["Home Loan", "Loan Against Property"],                     tenureRange: { min: 1, max: 20 }, eligibilityCriteria: { minIncome: 15000 } },
  { name: "Home First Finance",           type: "NBFC", riskCategory: "Medium", baseInterestRate: 10.25, processingFee: 1.00, maxLoanAmount: 5000000,  minCreditScore: 640, loanTypes: ["Home Loan"],                                             tenureRange: { min: 1, max: 20 }, eligibilityCriteria: { minIncome: 12000 } },
  { name: "Aptus Value Housing",          type: "NBFC", riskCategory: "Medium", baseInterestRate: 10.50, processingFee: 1.25, maxLoanAmount: 4000000,  minCreditScore: 640, loanTypes: ["Home Loan"],                                             tenureRange: { min: 1, max: 20 }, eligibilityCriteria: { minIncome: 12000 } },
  { name: "Repco Home Finance",           type: "NBFC", riskCategory: "Medium", baseInterestRate: 9.75,  processingFee: 0.75, maxLoanAmount: 5000000,  minCreditScore: 660, loanTypes: ["Home Loan", "Loan Against Property"],                     tenureRange: { min: 1, max: 20 }, eligibilityCriteria: { minIncome: 15000 } },
  { name: "Can Fin Homes",                type: "NBFC", riskCategory: "Low",    baseInterestRate: 8.80,  processingFee: 0.50, maxLoanAmount: 10000000, minCreditScore: 700, loanTypes: ["Home Loan"],                                             tenureRange: { min: 1, max: 30 }, eligibilityCriteria: { minIncome: 20000 } },
  { name: "DHFL (Restructured)",          type: "NBFC", riskCategory: "High",   baseInterestRate: 10.25, processingFee: 1.25, maxLoanAmount: 7500000,  minCreditScore: 660, loanTypes: ["Home Loan", "Loan Against Property"],                     tenureRange: { min: 1, max: 20 }, eligibilityCriteria: { minIncome: 20000 } },
];

const seedBanks = async () => {
  try {
    await Bank.deleteMany({});
    console.log("🗑️  Cleared existing bank data");

    const inserted = await Bank.insertMany(banks);
    console.log(`\n✅ Successfully seeded ${inserted.length} banks!\n`);

    // Summary by category
    const byType = banks.reduce((acc, b) => { acc[b.type] = (acc[b.type] || 0) + 1; return acc; }, {});
    const byRisk = banks.reduce((acc, b) => { acc[b.riskCategory] = (acc[b.riskCategory] || 0) + 1; return acc; }, {});
    console.log("📊 By Type:", byType);
    console.log("📊 By Risk:", byRisk);
    console.log("\n🏦 Banks include:");
    console.log("  - 12 Public Sector Banks (SBI, PNB, BoB, Canara...)");
    console.log("  - 21 Private Sector Banks (HDFC, ICICI, Axis, Kotak...)");
    console.log("  - 7  Small Finance Banks");
    console.log("  - 5  Foreign Banks (Citi, HSBC, Deutsche...)");
    console.log("  - 14 NBFCs/HFCs (Bajaj, Tata, LIC HFL, HDFC Ltd...)");
    console.log("  - 14 Digital/Fintech Lenders");
    console.log("  - 8  Housing Finance Companies");

    process.exit(0);
  } catch (err) {
    console.error("❌ Seeding failed:", err.message);
    process.exit(1);
  }
};

seedBanks();
